
name: node-app
namespace: helm-practice

replicas: 1
containers:
  image: chaitanyagidijala123/helm-learning
  tag: 1.1.0
  imagePullPolicy: IfNotPresent
  containerPort: 3000
  configMapRef:
    name: node-app-config
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"